project:
  type: website
  output-dir: _site

execute:
  project:
    type: julia
  cache: true

website:
  title: "Back to Blog Posts"
  favicon: "favicon.svg"
  
  navbar:
    logo-href: "../../blog"
    search: false

format:
  html:
    toc: true
    code-copy: true
    code-fold: false
    code-tools: true
    css: styles/custom.css
    include-in-header:
      - partials/umami-analytics.html
    include-before-body: 
      - partials/theme-init.html
    include-after-body:
      - partials/theme-toggle.html