#!/bin/bash
set -e

# Script to create a new Quarto blog post
# Usage: ./scripts/new_post.sh <post-name> [qmd|ipynb]
# Examples:
#   ./scripts/new_post.sh my-new-post
#   ./scripts/new_post.sh my-new-post qmd
#   ./scripts/new_post.sh my-new-post ipynb

if [ $# -lt 1 ]; then
    echo "Usage: $0 <post-name> [qmd|ipynb]"
    echo "Examples:"
    echo "  $0 my-new-post"
    echo "  $0 my-new-post qmd"
    echo "  $0 my-new-post ipynb"
    exit 1
fi

# Extract post name
POST_NAME=$1
POST_PATH="${POST_NAME}"
FORMAT=${2:-qmd}  # Default to qmd if not specified

# Validate format
if [ "$FORMAT" != "qmd" ] && [ "$FORMAT" != "ipynb" ]; then
    echo "Error: Format must be 'qmd' or 'ipynb'"
    exit 1
fi

POST_DIR="quarto_blog/posts/${POST_PATH}"

if [ -d "$POST_DIR" ]; then
    echo "Error: Directory $POST_DIR already exists"
    exit 1
fi

mkdir -p "$POST_DIR"

if [ "$FORMAT" = "qmd" ]; then
    cat > "$POST_DIR/index.qmd" << 'EOF'
---
title: "Post Title"
description: "Post description"
date: "DATE_PLACEHOLDER"
categories: []
---

## Introduction

Write your post content here.

<!-- 
Project.toml was created for this post.
- If this post is text-only (no Julia code), delete Project.toml
- If using Julia code, you may also need to create a Manifest.toml (automatically generated by Pkg)
- If using Python code, you may need to create a CondaPkg.toml (if using Python dependencies via CondaPkg)
-->
EOF
    # Replace date placeholder
    sed -i "s/DATE_PLACEHOLDER/$(date +%Y-%m-%d)/g" "$POST_DIR/index.qmd"
    echo "Created new post at $POST_DIR/index.qmd"
else
    # Create Jupyter notebook with freeze: false
    cat > "$POST_DIR/index.ipynb" << EOF
{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---\\n",
    "title: \\"Post Title\\"\\n",
    "description: \\"Post description\\"\\n",
    "date: \\"$(date +%Y-%m-%d)\\"\\n",
    "categories: []\\n",
    "---"
   ]
  },
   {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Introduction\\n",
    "\\n",
    "Write your post content here.\\n",
    "\\n",
    "<!-- \\n",
    "Project.toml was created for this post.\\n",
    "- If this post is text-only (no Julia code), delete Project.toml\\n",
    "- If using Julia code, you may also need to create a Manifest.toml (automatically generated by Pkg)\\n",
    "- If using Python code, you may need to create a CondaPkg.toml (if using Python dependencies via CondaPkg)\\n",
    "-->"
   ]
  }
 ],
 "metadata": {},
 "nbformat": 4,
 "nbformat_minor": 4
 }
EOF
    echo "Created new post at $POST_DIR/index.ipynb"
fi

# Create empty Project.toml for Julia environment
touch "$POST_DIR/Project.toml"
echo "Created empty Project.toml at $POST_DIR/Project.toml"

echo "Edit the file to customize your post"